test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -85,19 +85,19 @@ jobs:
 
           defconfigs=(
             k230_rtos_aihardware_defconfig
-            # k230_canmv_v1p0p1_defconfig
-            # k230_canmv_01studio_defconfig
-            # k230_canmv_dongshanpi_defconfig
-            # k230_canmv_lckfb_defconfig
-            # k230_canmv_rtt_evb_defconfig
-            # k230_canmv_v3p0_defconfig
-            # k230_rtos_evb_defconfig
-            # k230_rtos_evb_spinand_defconfig
-            # k230_canmv_labplus_1956_defconfig
-            # k230d_canmv_atk_dnk230d_defconfig
-            # k230d_canmv_bpi_zero_defconfig
-            # k230d_canmv_junroc_ai_cam_defconfig
-            # k230d_canmv_labplus_ai_camera_defconfig
+            k230_canmv_v1p0p1_defconfig
+            k230_canmv_01studio_defconfig
+            k230_canmv_dongshanpi_defconfig
+            k230_canmv_lckfb_defconfig
+            k230_canmv_rtt_evb_defconfig
+            k230_canmv_v3p0_defconfig
+            k230_rtos_evb_defconfig
+            k230_rtos_evb_spinand_defconfig
+            k230_canmv_labplus_1956_defconfig
+            k230d_canmv_atk_dnk230d_defconfig
+            k230d_canmv_bpi_zero_defconfig
+            k230d_canmv_junroc_ai_cam_defconfig
+            k230d_canmv_labplus_ai_camera_defconfig
           )
 
           for UBOOT_DEFCONFIG in "${defconfigs[@]}"; do
@@ -106,13 +106,14 @@ jobs:
             echo "=============================="
 
             base_name=${UBOOT_DEFCONFIG%_defconfig}
+            mkdir -p ~/artifacts/${base_name}
 
             make ${UBOOT_DEFCONFIG} || exit $?
             make uboot || exit $?
 
             # Also copy artifacts to artifacts folder
-            cp ${{ github.workspace }}/canmv_k230/output/${UBOOT_DEFCONFIG}/uboot/u-boot.bin ~/artifacts/${base_name}/u-boot.bin || echo "u-boot.bin missing" || exit $?
-            cp ${{ github.workspace }}/canmv_k230/output/${UBOOT_DEFCONFIG}/uboot/spl/u-boot-spl.bin ~/artifacts/${base_name}/u-boot-spl.bin || echo "u-boot-spl.bin missing" || exit $?
+            cp ${{ github.workspace }}/canmv_k230/output/${UBOOT_DEFCONFIG}/uboot/u-boot.bin ~/artifacts/${base_name}/u-boot.bin || echo "u-boot.bin missing"; exit $?
+            cp ${{ github.workspace }}/canmv_k230/output/${UBOOT_DEFCONFIG}/uboot/spl/u-boot-spl.bin ~/artifacts/${base_name}/u-boot-spl.bin || echo "u-boot-spl.bin missing"; exit $?
           done
 
           rm -rf ${{ github.workspace }}/canmv_k230/output/*
@@ -125,6 +126,7 @@ jobs:
             echo "=============================="
 
             base_name=${UBOOT_DEFCONFIG%_defconfig}
+            mkdir -p ~/artifacts/${base_name}
 
             echo "CONFIG_UBOOT_ENABLE_FAST_BOOT=y" >> ${{ github.workspace }}/canmv_k230/configs/${UBOOT_DEFCONFIG}
             echo "CONFIG_UBOOT_FAST_BOOT_RTSMART=y" >> ${{ github.workspace }}/canmv_k230/configs/${UBOOT_DEFCONFIG}
