Update github actions.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,19 +16,6 @@ jobs:
         shell: bash
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          path: uboot
-          fetch-depth: 1
-
-      - name: Get Git revision and set as environment variable
-        id: get_revision
-        run: |
-          cd ${{ github.workspace }}/uboot
-          revision=$(git describe --long --tag --dirty --always)
-          echo "REVISION=$revision" >> $GITHUB_ENV
-
       - name: Setup SSH
         run: |
           git config --global user.name kendryte747
@@ -36,6 +23,26 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.ACTIONS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+
+      - name: Checkout RTOS SDK
+        uses: actions/checkout@v4
+        with:
+          repository: kendryte/k230_rtos_sdk
+          path: ${{ github.workspace }}/rtos_sdk
+          fetch-depth: 1
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          path: ${{ github.workspace }}/rtos_sdk/src/uboot/uboot
+          fetch-depth: 1
+
+      - name: Get Git revision and set as environment variable
+        id: get_revision
+        run: |
+          cd ${{ github.workspace }}/rtos_sdk/src/uboot/uboot
+          revision=$(git describe --long --tag --dirty --always)
+          echo "REVISION=$revision" >> $GITHUB_ENV
 
       - name: Prepare Environment
         run: |
@@ -63,10 +70,8 @@ jobs:
 
       - name: Build Prebuilt u-boot
         run: |
-          cd ${{ github.workspace }}/uboot
+          cd ${{ github.workspace }}/rtos_sdk
           source ~/.canmv_venv/bin/activate
-          export ARCH=riscv
-          export CROSS_COMPILE=$HOME/.kendryte/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin/riscv64-unknown-linux-gnu-
 
           defconfigs=(
             k230_aihardware_defconfig
@@ -90,43 +95,25 @@ jobs:
             echo " Building U-Boot: ${UBOOT_DEFCONFIG}"
             echo "=============================="
 
-            base_name=${UBOOT_DEFCONFIG%_defconfig}
-
-            # Setup output directories
-            export SDK_UBOOT_BUILD_DIR=$HOME/build/${base_name}
-            mkdir -p ${SDK_UBOOT_BUILD_DIR}
-            mkdir -p ~/artifacts/${base_name}
-
-            # Build
-            make ${UBOOT_DEFCONFIG} O=${SDK_UBOOT_BUILD_DIR} || exit $?
-            make -j$(nproc) -C ${SDK_UBOOT_BUILD_DIR} || exit $?
+            make ${UBOOT_DEFCONFIG} || exit $?
+            make uboot || exit $?
 
             # Also copy artifacts to artifacts folder
-            cp ${SDK_UBOOT_BUILD_DIR}/u-boot.bin ~/artifacts/${base_name}/u-boot.bin || echo "u-boot.bin missing"
-            cp ${SDK_UBOOT_BUILD_DIR}/spl/u-boot-spl.bin ~/artifacts/${base_name}/u-boot-spl.bin || echo "u-boot-spl.bin missing"
+            cp ${{ github.workspace }}/output/${UBOOT_DEFCONFIG}/uboot/u-boot.bin ~/artifacts/${base_name}/u-boot.bin || echo "u-boot.bin missing"
+            cp ${{ github.workspace }}/output/${UBOOT_DEFCONFIG}/uboot/spl/u-boot-spl.bin ~/artifacts/${base_name}/u-boot-spl.bin || echo "u-boot-spl.bin missing"
           done
-
-          # build fastboot uboot
-          rm -rf ~/build
-          cp .github/workflows/sdk_autoconf.h.fastboot board/kendryte/common/sdk_autoconf.h
 
           for UBOOT_DEFCONFIG in "${defconfigs[@]}"; do
             echo "=============================="
-            echo " Building U-Boot: ${UBOOT_DEFCONFIG}"
+            echo " Building U-Boot With Fastboot: ${UBOOT_DEFCONFIG}"
             echo "=============================="
 
-            base_name=${UBOOT_DEFCONFIG%_defconfig}
+            echo "CONFIG_UBOOT_ENABLE_FAST_BOOT=y" >> ${{ github.workspace }}/rtos_sdk/configs/${UBOOT_DEFCONFIG}
+            echo "CONFIG_UBOOT_FAST_BOOT_RTSMART=y" >> ${{ github.workspace }}/rtos_sdk/configs/${UBOOT_DEFCONFIG}
+            make ${UBOOT_DEFCONFIG} || exit $?
+            make uboot || exit $?
 
-            # Setup output directories
-            export SDK_UBOOT_BUILD_DIR=$HOME/build/${base_name}
-            mkdir -p ${SDK_UBOOT_BUILD_DIR}
-            #mkdir -p ~/artifacts/${base_name}
-
-            # Build
-            make ${UBOOT_DEFCONFIG} O=${SDK_UBOOT_BUILD_DIR} || exit $?
-            make -j$(nproc) -C ${SDK_UBOOT_BUILD_DIR} || exit $?
-
-            cp ${SDK_UBOOT_BUILD_DIR}/spl/u-boot-spl.bin ~/artifacts/${base_name}/u-boot-spl-fastboot.bin || echo "u-boot-spl.bin missing"
+            cp ${{ github.workspace }}/output/${UBOOT_DEFCONFIG}/uboot/spl/u-boot-spl.bin ~/artifacts/${base_name}/u-boot-spl-fastboot.bin || echo "u-boot-spl.bin missing"; exit $?
           done
 
       - uses: actions/upload-artifact@v4
@@ -137,14 +124,8 @@ jobs:
           if-no-files-found: error
           compression-level: 0
 
-      - name: Checkout RTOS SDK
-        uses: actions/checkout@v4
-        with:
-          repository: kendryte/k230_rtos_sdk
-          path: rtos_sdk
-          fetch-depth: 1
-
       - name: Install Prebuilt u-boot
+        if: github.ref != 'refs/heads/dev'
         run: |
           # Capture the U-Boot commit hash
           cd ${{ github.workspace }}/uboot
